import os
import sys
import json
from pathlib import Path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
# ----------- local imports ----------- 
from constants import DATA_DIR

import pandas as pd
import numpy as np
import pickle   


def read_datastore_embeddings(datastore_path = DATA_DIR / "face_identification/train/ds_model_facenet512_detector_opencv_aligned_normalization_base_expand_0.pkl" ):
    """ 
    Args:
        datastore_path: Path = path of pickle file generated by deepface find
    """
    # read file
    with open(datastore_path, "rb") as f:
            representations = pickle.load(f)
    # convert represtations to df        
    df_rep = pd.DataFrame(representations)
    # add person column
    df_rep['person'] = df_rep['identity'].apply(lambda x: Path(x).parent.name)
    
    return df_rep

def get_avg_person_embeddings(df: pd.DataFrame):
    """ 
    group df by person and return average embeddings foreach person
    Args:
        df: DataFrame
            - dataframe with two columns ['person', 'embeddings']
    """
    return df.groupby("person", as_index=False).agg({
        "embedding": lambda x: np.mean(np.stack(x), axis=0)  # Average embeddings
    })
